### ISSUE TITLE
$conn是否忘记修改了，应该为$this->connection

### ISSUE THREAD

**Issue by SyanH** [mix-php/session#1]
https://github.com/mix-php/session/blob/176935f2fc3622750cc0725116a698dcb4c21ac9/src/RedisHandler.php#L56

**Comment by onanying** [comment]
是的，应该是替换的时候替换错了

**Comment by onanying** [comment]
改好了 https://github.com/mix-php/session/blob/v2.1/src/RedisHandler.php
